name: CI Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: nextjs

      - name: Lint code
        run: npm run lint
        working-directory: nextjs

      - name: Run Prettier
        run: npm run prettier
        working-directory: nextjs

      - name: Build project
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: npm run build
        working-directory: nextjs

      - name: Run tests
        env:
          SUPPRESS_JEST_WARNINGS: true
        run: npm test
        working-directory: nextjs
