name: CI Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: cd nextjs && npm ci

      - name: Lint code
        run: cd nextjs && npm run lint

      - name: Run Prettier
        run: cd nextjs && npm run prettier

      - name: Build project
        run: cd nextjs && npm run build

      - name: Run tests
        run: cd nextjs && npm test
